/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.4/samples
 */
plugins{
 alias(libs.plugins.kotlinMultiplatform) apply false
 alias(libs.plugins.androidLibrary) apply false
 alias(libs.plugins.jetbrainsCompose) apply false
 alias(libs.plugins.androidApplication) apply false
 alias(libs.plugins.kotlinAndroid) apply false
}
