/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.4/userguide/building_swift_projects.html in the Gradle documentation.
 */
 enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
 
 pluginManagement {
  repositories {
   maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
   google()
   gradlePluginPortal()
   mavenCentral()
  }
 }
 
 dependencyResolutionManagement {
  repositories {
   google()
   mavenCentral()
   maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
  }
 }

rootProject.name = "FleetDemo"
include(":common")
include(":androidApp")
include(":webApp")